### ISSUE TITLE
How to store on disk an in-memory zarr

### ISSUE THREAD

**Issue by mratsim** [alimanfoo/zarr#100]
Hi alimanfoo,

Great work on your library. I have a library (vtk for medical image visualization) that outputs a 3D numpy array.
I want to store it on disk however it doesn't seem like there is a "convert", "save" or export function.

I tried using the following as well:
data is a 3d numpy array
outFile is path/to/my/image.zarr

    z = zarr.array(data,
        **path=outFile**, dtype='int16',
        chunks=(100, 100, 100), compression='blosc', compression_opts=dict(cname='zstd'))

I get no error, z is created in memory, but nothing on disk.

For reference bcolz has a rootdir parameter that seems to be able to do what I want.

**Comment by alimanfoo** [comment]
Hi Mamy,

The easiest way to create a Zarr array using the filesystem for storage is to use the [open_array](http://zarr.readthedocs.io/en/latest/api/creation.html#zarr.creation.open_array) function. There is an example in the tutorial section on [persistent arrays](http://zarr.readthedocs.io/en/latest/tutorial.html#persistent-arrays).

If you have several arrays you want to store on disk, you might find it convenient to use [groups](http://zarr.readthedocs.io/en/latest/tutorial.html#groups). The easiest way to create a persistent group via the [open_group](http://zarr.readthedocs.io/en/latest/api/hierarchy.html#zarr.hierarchy.open_group) function.

Both [open_array](http://zarr.readthedocs.io/en/latest/api/creation.html#zarr.creation.open_array) and [open_group](http://zarr.readthedocs.io/en/latest/api/hierarchy.html#zarr.hierarchy.open_group) are actually convenience function. An alternative way of creating on-disk arrays is to pass a [DirectoryStore](http://zarr.readthedocs.io/en/latest/api/storage.html#zarr.storage.DirectoryStore) as the value of the `store` keyword argument to any of the [array creation](http://zarr.readthedocs.io/en/latest/api/creation.html) functions. E.g.::

```python
import zarr
store = zarr.DirectoryStore('/path/to/data')
z = zarr.array(data, store=store, dtype='int16', chunks=(100, 100, 100), compressor=zarr.Blosc(cname='zstd'))
```

Hth.

**Comment by mratsim** [comment]
Thank you very much,

Your DirectoryStore example worked.
Using open_array or open_group wouldn't work as easily as I would have to compute the proper shape to pass it as a parameter and then copy the NumPy array into the Zarr array.

Looking at the documentation, there is actually this example that I missed:
```python
store = zarr.ZipStore('example.zip', mode='w')
z = zarr.zeros((1000, 1000), chunks=(100, 100), dtype='i4', store=store) 
```
but there is no example with exporting/writing an existing array to a DirectoryStore.

I'm creating a PR for that.
