### ISSUE TITLE
CI issues related to appdirs

### ISSUE THREAD

**Issue by alimanfoo** [alimanfoo/zarr#125]
Looks like the appdirs issue has appeared again: https://travis-ci.org/alimanfoo/zarr/jobs/204972534

Suggest we remove appdirs from the pinned dev requirements file and let pip/setuptools install whichever version it wants.

**Comment by jakirkham** [comment]
Also here are some related issues ( https://github.com/ActiveState/appdirs/issues/89 ) and ( https://github.com/pypa/pip/issues/4264 ).

**Comment by jakirkham** [comment]
Proposing we unpin all of `setuptools` requirements in PR ( https://github.com/alimanfoo/zarr/pull/126 ).
