### ISSUE TITLE
Release 2.2

### ISSUE THREAD

**Issue by jakirkham** [alimanfoo/zarr#144]
Was wondering what the status was on releasing 2.2. There seem to be several things scheduled for 2.2, but am unsure if they are all required. Are there things you need help with?

**Comment by jakirkham** [comment]
Any thoughts on this @alimanfoo?

**Comment by alimanfoo** [comment]
Thank you for the offer, apologies I'm under a deadline and have had to put OSS on hold for the moment.

FWIW The next thing I wanted to do for the 2.2 release was to set up a data fixture (#138) which would provide some protection against any regressions that accidentally break backwards compatibility with the data format. That would then allow safe merging of the numcodecs refactoring work (#139, #74). 

Apart from that, the following I would classify as high priority for 2.2. These are mostly boring but important bug fixes, except for the tree printing which is very exciting :-) ... 
* Group print hierarchy (#140, #82)
* Index with numpy int64 #143
* Various repr tweaks (#132, #115, #83)
* Specification for datetime dtypes is ambiguous #85
* Don't include partial files when counting initialized chunks #97

The following would be nice to have but could live without for this release:
* Usability tweaks to zarr.open (https://github.com/alimanfoo/zarr/issues/141, https://github.com/alimanfoo/zarr/issues/105)
* Adding attrs arg to create_group and create_dataset #121
* Add a save() function similar to numpy.save/numpy.savez #104
* Tweak and doc chunks kwarg (#106, #107)
* Copy method #113
* Group.put() #81
* Compute hash of array #98
* Key encoding for dbm-style databases #133
* Some doc improvements (#103, #91, #131)

There are also a set of issues relating to indexing (#89, #93, #78, #116, #119). It would be nice to resolve all these together with some reworking of the indexing code. The code you have in kenjutsu is nice and I'd really like to draw on that, but I think there are some performance bottlenecks in there which could manifest in Zarr if we just depend on kenjutsu as-is, and I wanted to explore some options. This may all be best left for a subsequent release, it's not a small piece of work.

**Comment by alimanfoo** [comment]
Tracking release 2.2 via: https://github.com/alimanfoo/zarr/milestone/5
