### ISSUE TITLE
Datasets don't work when dtype=object

### ISSUE THREAD

**Issue by xtianpoli** [alimanfoo/zarr#145]
The following code sequence raise  a "ValueError: cannot create an OBJECT array from memory buffer" when z is acceded (i.e. copied into a numpy.ndarray) after being assigned. The same code works fine when dtype='i8'
##################################
import zarr
root_group = zarr.group()
z = root_group.create_dataset('foo', shape=(1,),
                             chunks=(256,), dtype='object',
                             fill_value=None, compression='gzip',
                             compression_opts=1)
z[:] = 5
print(z[:])

##################################

**Comment by alimanfoo** [comment]
Hi there,

For object arrays some encoding is required. There are two codecs available from a separate package called numcodecs which can be used with the current (2.1.4) release of Zarr. E.g.:

```python
>>> import zarr
>>> import numcodecs
>>> zarr.__version__
'2.1.4'
>>> numcodecs.__version__
'0.2.1'
>>> zarr.codecs.codec_registry[numcodecs.Pickle.codec_id] = numcodecs.Pickle
>>> zarr.codecs.codec_registry[numcodecs.MsgPack.codec_id] = numcodecs.MsgPack
>>> z = zarr.create(shape=10, chunks=2, dtype=object, compression='gzip', compression_opts=1, filters=[numcodecs.Pickle()])
>>> z[:] = 42
>>> z[:]
array([42, 42, 42, 42, 42, 42, 42, 42, 42, 42], dtype=object)
>>> z = zarr.create(shape=10, chunks=2, dtype=object, compression='gzip', compression_opts=1, filters=[numcodecs.MsgPack()])
>>> z[:] = 42
>>> z[:]
array([42, 42, 42, 42, 42, 42, 42, 42, 42, 42], dtype=object)
```

As of Zarr 2.2 this will be a bit more convenient as it will not be necessary to register the Pickle and MsgPack codecs.

Hth.

**Comment by xtianpoli** [comment]
Thanks a lot!

2017-04-25 12:26 GMT+02:00 Alistair Miles <notifications@github.com>:
