### ISSUE TITLE
v2.2 release notes

### ISSUE THREAD

**Issue by alimanfoo** [alimanfoo/zarr#159]
TODO:

* [ ] numcodecs change #139
* [ ] visitor pattern #122 
* [ ] astype #96, #120
* [ ] bug fixes, maintenance #95, #123, #114, #118, #146, ...

**Comment by jakirkham** [comment]
Any thoughts on the items mentioned in issue ( https://github.com/alimanfoo/zarr/issues/144 )?

**Comment by alimanfoo** [comment]
I'm hoping to resolve some more of the items in #144 before making the 2.2 release. This issue is to remind me to write release notes for the changes already merged.

**Comment by jakirkham** [comment]
Ok, just noticed activity picked up here and wasn't sure what sort of timeline you had in mind for releasing. 😉 Might try and give the tree work another look (am feeling inspired). 😄

**Comment by alimanfoo** [comment]
Re timeline, I'm thinking maybe 4 weeks, to give some to work through a few more issues.
