### ISSUE TITLE
Further tests for structured arrays

### ISSUE THREAD

**Issue by alimanfoo** [alimanfoo/zarr#178]
More tests are needed for basic functionality for arrays with structured dtype, including fill value, 0d array.

**Comment by jakirkham** [comment]
Out of curiosity, are there existing tests for structured arrays somewhere?

**Comment by jakirkham** [comment]
Looks like there were some structured array tests including with fill value already. However there wasn't a test for 0-D structured arrays. So tweaked the existing tests to include the 0-D case. Put this together as PR ( https://github.com/alimanfoo/zarr/pull/210 ).
